### PR TITLE
updated the weapon classes and fixed formatting

### PR DESCRIPTION
**Pull request by ingax01**
added missing weapons and fixed their formatting

### CODE REVIEW

**Comment by Raffson** [comment]
Have you added the weapons manually? Or was it the the result of a pydcs-export?

Also, formatting is done with `black`, which is currently complaining about the changes you made 😅

Hmu if you have any questions or need any help 😉

**Comment by ingax01** [comment]
> Have you added the weapons manually? Or was it the the result of a pydcs-export?

it was the result of a pydcs-export, after that i formatted them 

> Also, formatting is done with `black`, which is currently complaining about the changes you made 😅

sorry about that, im new to this project, github and contributing as a whole; what do you mean with `black`?

> Hmu if you have any questions or need any help 😉

how could i do that?, is there i discord server i could join?

**Comment by Raffson** [comment]
No worries, your work so far is appreciated regardless 😁

Anyway, `black` is a formatting tool which you should be able to install with `pip`, which should already be installed if you set up your virtual environment and ran `pip install -r requirements.txt`.

We also have a discord server you can join: https://discord.gg/b4x34Bg4We

I'm currently at work so I may not answer immediately, so I'll try to answer your questions as soon as I'm home 😉

**Review by Raffson — APPROVED** [review]

**Comment by Raffson** [comment]
Just to verify, was the export based on V2.1.12 beta of the Su30?

**Comment by ingax01** [comment]
yes, it was based on the latest public build

**Pull request merged**
