### PR TITLE
Splashdamage F-4E update

### PR DESCRIPTION
**Pull request by tmz42**
Update for the Splash Damage plugin, including weapons for the Heatblur F-4E.

- HOBOS : set to same value as AGM-130/GBU-10/GBU-24
- Bullpups : set to 68 for A/B (same as small Mavericks and other 250lb weapons), set to 528 for 970lb C model
- Walleyes : set to 68 for I model (same as small Mavericks and other 250lb weapons), no change for the Walleye II model

### CODE REVIEW

**Comment by Raffson** [comment]
I have actually pushed some additions myself which seem to conflict. I'll try to sort out the merge conflicts tomorrow, unless you want to give it a shot?

**Comment by Starfire13** [comment]
There are some issues with the values for the Walleye I and the Bullpup A and B. All three are set to 68 kg (150 lbs), which is way too low. The Walleye I has a 374kg (825 lb) warhead, and the Bullpup A and B have 113 kg (250 lb) warheads.

**Comment by tmz42** [comment]
Hi, I modified some values according to online sources and Janes.

**Comment by tmz42** [comment]
> I have actually pushed some additions myself which seem to conflict. I'll try to sort out the merge conflicts tomorrow, unless you want to give it a shot?

Regarding the additions, what were you thinking about?

**Review by Raffson — APPROVED** [review]

**Pull request merged**
