### PR TITLE
Payloads corrections and additions

### PR DESCRIPTION
**Pull request by Turbolious**
Corrected most Vietnam era payloads and added missing ones.

### CODE REVIEW

**Comment by MetalStormGhost** [comment]
Would it be possible to list the new loadouts here in text format, so I don't need to look each CLSID up individually?

**Comment by Turbolious** [comment]
A4 As follows

image
image
image
image
image
image
image
image
image
image
image

A7 as follows 

image
image
image
image
image
image
image
image

OV-10A as follows

image
image
image
image
image
image

F-5E as follows

image
image
image
image
image
image
image
image
image

**Comment by Turbolious** [comment]
A-6 as follows (Will add missing payloads on next pass)

image
image
image
image
image

F-104C as follows

image
image
image
image

F-104G as follows 

image
image
image
image
image
image
image
image
image
image

F-105G as follows

image
image
image
image
image
image
image
image

VSN F-4B as follows

image
image
image
image
image
image

VSN F-4C as follows

image
image
image
image
image

**Comment by Turbolious** [comment]
I have some small updates and corrections for these that will follow in another pull

**Pull request closed without merging**
